apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "remediator.fullname" . }}-catalog
  labels:
    {{- include "remediator.labels" . | nindent 4 }}
data:
  fault-catalog.json: |
{{ .Files.Get "files/fault-catalog.json" | indent 4 }}
