{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "worker-service.fullname" . }}
  labels:
    {{- include "worker-service.labels" . | nindent 4 }}
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      {{- include "worker-service.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
