package main

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"os"
	"strconv"
	"sync"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"github.com/tomjga/OmniObserve/services/shared/telemetry"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
)

var version = "dev"

type config struct {
	TargetURL  string
	Workers    int
	Interval   time.Duration
	ListenAddr string
}

var (
	requestsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "worker_requests_total",
			Help: "Synthetic workload requests generated by worker-service.",
		},
		[]string{"code", "result"},
	)
	requestDuration = prometheus.NewHistogram(
		prometheus.HistogramOpts{
			Name:    "worker_request_duration_seconds",
			Help:    "Synthetic workload request duration.",
			Buckets: prometheus.DefBuckets,
		},
	)
)

func init() {
	prometheus.MustRegister(requestsTotal, requestDuration)
}

func main() {
	cfg := configFromEnv(os.Getenv)
	shutdownTracer, err := telemetry.InitTracer(context.Background(), "worker-service", version)
	if err != nil {
		panic(err)
	}
	defer func() { _ = shutdownTracer(context.Background()) }()

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	client := &http.Client{Timeout: 5 * time.Second}
	var wg sync.WaitGroup
	for i := 0; i < cfg.Workers; i++ {
		wg.Add(1)
		go func(id int) {
			defer wg.Done()
			runWorker(ctx, client, cfg, id)
		}(i)
	}

	mux := http.NewServeMux()
	mux.HandleFunc("/healthz", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_, _ = fmt.Fprintf(w, `{"status":"ok","version":%q,"target":%q}`+"\n", version, cfg.TargetURL)
	})
	mux.Handle("/metrics", promhttp.Handler())

	if err := http.ListenAndServe(cfg.ListenAddr, mux); err != nil {
		cancel()
		wg.Wait()
		panic(err)
	}
}

func configFromEnv(getenv func(string) string) config {
	return config{
		TargetURL:  envStr(getenv, "WORKER_TARGET_URL", "http://api-service:8080/benchmark?max_delay=25"),
		Workers:    envInt(getenv, "WORKER_CONCURRENCY", 2),
		Interval:   time.Duration(envInt(getenv, "WORKER_INTERVAL_MS", 500)) * time.Millisecond,
		ListenAddr: envStr(getenv, "WORKER_LISTEN_ADDR", ":8080"),
	}
}

func envStr(getenv func(string) string, key, def string) string {
	if v := getenv(key); v != "" {
		return v
	}
	return def
}

func envInt(getenv func(string) string, key string, def int) int {
	if v := getenv(key); v != "" {
		n, err := strconv.Atoi(v)
		if err == nil && n > 0 {
			return n
		}
	}
	return def
}

func runWorker(ctx context.Context, client *http.Client, cfg config, id int) {
	ticker := time.NewTicker(cfg.Interval)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			doRequest(ctx, client, cfg.TargetURL, id)
		}
	}
}

func doRequest(ctx context.Context, client *http.Client, target string, workerID int) {
	tracer := otel.Tracer("worker-service")
	ctx, span := tracer.Start(ctx, "synthetic_request")
	defer span.End()
	span.SetAttributes(
		attribute.String("http.url", target),
		attribute.Int("worker.id", workerID),
	)

	start := time.Now()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, target, nil)
	if err != nil {
		record("0", "request_error", start)
		span.RecordError(err)
		return
	}
	resp, err := client.Do(req)
	if err != nil {
		record("0", "transport_error", start)
		span.RecordError(err)
		return
	}
	defer resp.Body.Close()
	_, _ = io.Copy(io.Discard, resp.Body)

	code := strconv.Itoa(resp.StatusCode)
	result := "success"
	if resp.StatusCode >= 500 {
		result = "server_error"
	} else if resp.StatusCode >= 400 {
		result = "client_error"
	}
	span.SetAttributes(attribute.Int("http.status_code", resp.StatusCode))
	record(code, result, start)
}

func record(code, result string, start time.Time) {
	requestsTotal.WithLabelValues(code, result).Inc()
	requestDuration.Observe(time.Since(start).Seconds())
}
